version: '3.8'
services:
  user-account-service:
    build: .
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - game-system-network
networks:
  game-system-network:
    external: true