// RabbitMQ Service Name
export const USER_ACCOUNT_SERVICE_RABBIT_MQ = 'USER_ACCOUNT_SERVICE_RABBIT_MQ';

// RabbitMQ Queue Name
export const USER_ACCOUNT_QUEUE = 'USER_ACCOUNT_QUEUE';

// Massage Pattern
export const USER_ACCOUNT = {
  GET_USER_ACCOUNT: 'GET_USER_ACCOUNT',
  CREATE_USER_ACCOUNT: 'CREATE_USER_ACCOUNT',
  UPDATE_USER_ACCOUNT: 'UPDATE_USER_ACCOUNT',
  DELETE_USER_ACCOUNT: 'DELETE_USER_ACCOUNT',
};
