// RabbitMQ Client Service Name
export const USER_ACCOUNT_SERVICE_CLIENT = 'USER_ACCOUNT_SERVICE_CLIENT';
export const LOBBY_SERVICE_CLIENT = 'LOBBY_SERVICE_CLIENT';

// RabbitMQ Queue Name
export const USER_ACCOUNT_QUEUE = 'USER_ACCOUNT_QUEUE';
export const LOBBY_QUEUE = 'LOBBY_QUEUE';

// Massage Pattern
export const USER_ACCOUNT = {
  GET_USER_ACCOUNT: 'GET_USER_ACCOUNT',
  CREATE_USER_ACCOUNT: 'CREATE_USER_ACCOUNT',
  UPDATE_USER_ACCOUNT: 'UPDATE_USER_ACCOUNT',
  DELETE_USER_ACCOUNT: 'DELETE_USER_ACCOUNT',
};

export const LOBBY = {
  GET_LOBBY: 'GET_LOBBY',
  CREATE_LOBBY: 'CREATE_LOBBY',
  UPDATE_LOBBY: 'UPDATE_LOBBY',
  DELETE_LOBBY: 'DELETE_LOBBY',
};
